// Generated by https://quicktype.io

export interface Catergoris {
  id: number;
  name: string;
}
// Generated by https://quicktype.io

export interface Products {
  id: number;
  name: string;
  products: Product[];
}

export interface Product {
  id: number;
  name: string;
  price: number;
  nuts: boolean;
  image: string;
  vegeterian: boolean;
  spiciness: number;
  categoryId: number;
}
